package org.project.proxibank.security.mapping;

public enum ErrorName {
	USER_TOKEN_REQUIRED,
	USER_PASSWORD_REQUIRED,
	
	USER_INVALID_TOKEN,
	USER_INVALID_TOKEN_TIME,
	USER_INVALID_PASSWORD,
	USER_INVALID_CREDENTIALS,
	
	USER_NOT_FOUND,
	USER_ALREADY_EXIST,
	USER_DISABLED,
	
	USER_FORBIDDEN_SUPER_ADMIN
}
